/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.7).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;
import io.swagger.annotations.AuthorizationScope;
import io.swagger.model.ClientApp;
import io.swagger.model.ClientAppUpdateRequest;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-04-15T15:14:44.820Z[GMT]")
@Api(value = "client-apps", description = "the client-apps API")
public interface ClientAppsApi {

    @ApiOperation(value = "Delete Client App", nickname = "deleteClientApp", notes = "", authorizations = {
            @Authorization(value = "BearerAuth"),
            @Authorization(value = "OAuth2", scopes = {
                    @AuthorizationScope(scope = "", description = "")})}, tags = {"Client Apps",})
    @ApiResponses(value = {
            @ApiResponse(code = 204, message = "Success")})
    @RequestMapping(value = "/client-apps/{id}",
            method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteClientApp(@ApiParam(value = "", required = true) @PathVariable("id") Integer id);

    @ApiOperation(value = "Get client apps", nickname = "getClientApps", notes = "", response = ClientApp.class, responseContainer = "List", authorizations = {
            @Authorization(value = "BearerAuth"),
            @Authorization(value = "OAuth2", scopes = {
                    @AuthorizationScope(scope = "", description = "")})}, tags = {"Client Apps",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Success", response = ClientApp.class, responseContainer = "List")})
    @RequestMapping(value = "/client-apps",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<ClientApp>> getClientApps(@ApiParam(value = "Specify what extra fields to include in the response.", allowableValues = "accessId, connected") @Valid @RequestParam(value = "include", required = false) List<String> include);

    @ApiOperation(value = "Update client app", nickname = "updateClientApp", notes = "", response = ClientApp.class, authorizations = {
            @Authorization(value = "BearerAuth"),
            @Authorization(value = "OAuth2", scopes = {
                    @AuthorizationScope(scope = "", description = "")})}, tags = {"Client Apps",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Success", response = ClientApp.class)})
    @RequestMapping(value = "/client-apps/{id}",
            produces = {"application/json"},
            consumes = {"application/json"},
            method = RequestMethod.PUT)
    ResponseEntity<ClientApp> updateClientApp(@ApiParam(value = "", required = true) @Valid @RequestBody ClientAppUpdateRequest body, @ApiParam(value = "", required = true) @PathVariable("id") Integer id);

}
