/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.7).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;
import io.swagger.annotations.AuthorizationScope;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-04-15T15:14:44.820Z[GMT]")
@Api(value = "token-info", description = "the token-info API")
public interface TokenInfoApi {

    @ApiOperation(value = "Returns information about used access token", nickname = "getTokenInfo", notes = "", response = Object.class, authorizations = {
            @Authorization(value = "BearerAuth"),
            @Authorization(value = "OAuth2", scopes = {
                    @AuthorizationScope(scope = "", description = "")})}, tags = {"Server",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Success", response = Object.class)})
    @RequestMapping(value = "/token-info",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Object> getTokenInfo();

}
