/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.7).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;
import io.swagger.annotations.AuthorizationScope;
import io.swagger.model.UserData;
import io.swagger.model.UserUpdateRequest;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-04-15T15:14:44.820Z[GMT]")
@Api(value = "users", description = "the users API")
public interface UsersApi {

    @ApiOperation(value = "Get current user", nickname = "getCurrentUser", notes = "", response = UserData.class, authorizations = {
            @Authorization(value = "BearerAuth"),
            @Authorization(value = "OAuth2", scopes = {
                    @AuthorizationScope(scope = "", description = "")})}, tags = {"Users",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Success", response = UserData.class)})
    @RequestMapping(value = "/users/current",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<UserData> getCurrentUser();

    @ApiOperation(value = "Update current user", nickname = "updateCurrentUser", notes = "", authorizations = {
            @Authorization(value = "BearerAuth"),
            @Authorization(value = "OAuth2", scopes = {
                    @AuthorizationScope(scope = "", description = "")})}, tags = {"Users",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Success")})
    @RequestMapping(value = "/users/current",
            consumes = {"application/json"},
            method = RequestMethod.PATCH)
    ResponseEntity<Void> updateCurrentUser(@ApiParam(value = "", required = true) @Valid @RequestBody UserUpdateRequest body);

}
