springfox.documentation.swagger.v2.path: /api-docs
server:
  servlet.context-path: /api/v2.3.0
  port: 9090
spring.jackson:
  date-format: io.swagger.RFC3339DateFormat
  serialization.WRITE_DATES_AS_TIMESTAMPS: false
logging.level:
  root: WARN
  org.springframework.web: INFO
  io.swagger: INFO
  pl.grzeslowski: INFO
jsupla:
  token: MzFhYTNiZTAwODg5M2E0NDE3OGUwNWE5ZjYzZWQ2YzllZGFiYWRmNDQwNDBlNmZhZGEzN2I3NTJiOWM2ZWEyZg